import mechanicalsoup
import argparse 
from time import sleep
import sys


parser = argparse.ArgumentParser(description="Login to SPOJ.")
parser.add_argument("username") # FOR TAKING USERNAME
parser.add_argument("password") # FOR TAKING PASSWORD
args = parser.parse_args()
print("Wait we are logging you in......")

#LANGUAGE LIST OF SUBMITTING SOLUTION
langlist = []
langlist.append({'C(gcc 6.3)':'1'})
langlist.append({'C++(gcc 4.3.2)':'41'})
langlist.append({'C++(gcc 6.3)':'11'})
langlist.append({'C++14(gcc 6.3)':'44'})
langlist.append({'C#(gmcs 4.6.2)':'27'})
langlist.append({'Java(HotSpot 8u112)':'10'})
langlist.append({'Python(cpython 2.7.2)':'4'})
langlist.append({'Python(PyPy 2.6.0)':'99'})
langlist.append({'Python3(python 3.5)':'116'})

browser = mechanicalsoup.StatefulBrowser(soup_config={'features': 'lxml'})
login_page = browser.open("https://spoj.com/login") #LOGIN PAGE
login_page.raise_for_status()

# GETTING LOGIN PAGE FORM
login_form = mechanicalsoup.Form(login_page.soup.select_one('form'))

# FILLING DETAILS LIKE USERNAME AND PASSWORD 
login_form.input({"login_user": args.username, "password": args.password})

# SUBMITTING THE FORM
page2 = browser.submit(login_form, login_page.url)
profile = browser.open('https://www.spoj.com/myaccount/')
authentication = browser.get_current_page().find('button').text


#PATH VARIABLE 
path=''
#PROBLEM CODE VARIABLE
problem_code=''


def submission_go():
	#PROBLEM CODE WHICH HAS TO BE SUBMITTED 
	problem_code = input("Enter the problem code! ")
	#OPENING SUBMISSION PAGE 
	submit_page = browser.open("https://www.spoj.com/submit/" + problem_code)
	opened = browser.get_current_page().find('title').text
	#VALIDATING PROBLEM CODE
	if(opened=='404 Not Found'):
		#WRONG TEST CODE
		print('INVALID PROBLEM CODE !!!!')
		submission_go()



#VALIDATION OF LOGIN CREDENTIAL
if(authentication==' sign in'):
	#WRONG ID OR PASSWORD GIVEN
	print('!!!!   WRONG CREDENTIAL  !!!!!')
	sys.exit()
else:
	# LOGIN SUCCESSFUL
	print('You logged in successfully......')
	submission_go()


#OPEN SUBMISSION PAGE
submit_1= browser.get_current_page().find('submit',id='submit_form')


#SELECTING THE FORM
form = browser.select_form()
form.choose_submit(submit_1)


i=1
#LANGUAGE LIST DISPLAYED
for lang in langlist:
	for key in lang:
		print("%d. %s" % (i,key))
	i+=1


#FUNCTION FOR SELECTING LANGUAGE FOR THE SUBMISSION
def language_selecton():
	try:
		#ASKING USER ABOUT THE LANGUAGE
		print("Select Your Language : ")
		Language = int(input())

		#GETTING THE LANGUAGE AND ITS VALUE
		key,value = (langlist[Language-1]).popitem()

		#SELECTING LANGUAGE IN THE FORM
		form.set("lang",value)
	except:
		print('!!!  WRONG LANGUAGE SELECTION  !!!')
		language_selecton()
	
	
#CALLING LANGUAGE SELECTION FUNCTION
language_selecton()


#SELECTING THE PATH WHERE THE SOLUTION IS PRESENT 
def path_selection():
	#VALIDATING THE PATH
	try:
		#TAKING PATH OF THE SOLUTION
		path = input('Give your file path along with name and extension: ')

		#OPENING THE FILE OF THE GIVEN PATH
		fil = open(path).read()

		#UPLOADING THE FILE 
		form.set("subm_file",path)
	except:
		print('!!!!!   INVALID PATH  !!!!!')
		path_selection()



path_selection()

#SUBMITTING THE CODE
browser.submit_selected()

print("Your Code is Running .........")
#PAUSE THE CODE FOR 10 SECONDS FOR THE EVALUATION OF THE CODE
sleep(10)

#GETTING THE USERNAME TO ACCESS THE USER SUBMISSION STATUS PAGE
username_a = args.username

#STATUS PAGE 
answer_page = browser.open('https://www.spoj.com/status/'+problem_code+','+username_a+'/')

#SUBMISSION ID RANDOMLY GENERATED BY SPOJ!!!
submission_id = browser.get_current_page().find('table').find('a').text

#DISPLAYING THE RESULT OF CODE 
print('Result of Your Solution..........')
answer = browser.get_current_page().find('td' , class_= 'statusres text-center').text.split()
answer.pop()
answer.pop()
answer.pop()
print(*answer , sep=' ')
